logging:
  level:
    org.springframework: DEBUG
    com.mkyong: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: inam
        url: jdbc:postgresql://localhost:5432/SG001
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    main:
        banner-mode: 'off'
    profiles:
        active: dev